name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv my-venv
          source my-venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log start time
        run: echo "$(date -Iminutes)" > tests-log.txt

      - name: Run tests
        run: |
          source my-venv/bin/activate
          pytest tests/ | tee -a tests-log.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-results
          path: tests-log.txt
